# Generated by Django 2.2.16 on 2020-09-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200911_0701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
