# Generated by Django 2.2.16 on 2020-09-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200911_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipe.Unit'),
        ),
    ]
