# Generated by Django 2.2.16 on 2020-09-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200912_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to='recipe.Ingredient'),
        ),
    ]
