# Generated by Django 2.2.16 on 2020-09-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20200912_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='quantity',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='units',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipe.Unit'),
        ),
    ]
